
FROM node:18-alpine
WORKDIR /app

COPY ./ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY ./ui .

# Build the React app
RUN npm run build

# Expose port 3000 to the outside world
EXPOSE 3000

# Command to run the React app
CMD ["npm", "start"]
